export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOADING = 'USER_LOADING';

export const NAV_STATE_CHANGE = 'NAV_STATE_CHANGE';

export const CHANGE_SEARCH_VALUE = 'CHANGE_SEARCH_VALUE';
